[package]
name = "server"
version = "0.1.0"
authors = ["russoturisto <russoturisto@gmail.com>"]

[dependencies]
byteorder = "1"
common = { path = "../common" }
futures = "^0"
smallvec = "^0"
tokio = "^0"
tokio-codec = "^0"
tokio-core = "^0"
tokio-io = "^0"
