pub const RESPONSE_INVALID_FLAG: u8 = 128;
pub const RESPONSE_INVALID_DATA_FORMAT_FLAG: u8 = 1;
pub const RESPONSE_INVALID_GLOBAL_CATEGORY_ID_FLAG: u8 = 2;
pub const RESPONSE_INVALID_CATEGORY_CACHE_INDEX_FLAG: u8 = 3;
pub const RESPONSE_INVALID_GLOBAL_LOCATION_ID_FLAG: u8 = 4;
pub const RESPONSE_INVALID_LOCATION_CACHE_INDEX_FLAG: u8 = 5;
pub const RESPONSE_INVALID_PERIOD_ID_FLAG: u8 = 6;
pub const RESPONSE_INVALID_TIMEZONE_ID_FLAG: u8 = 7;