pub const NUM_TIMEZONES: usize = 38;
pub const NUM_TIMEZONES_WITH_GLOBAL_CATEGORY: usize = NUM_TIMEZONES + 1;

/**  Time zones **/
//UTC Offset	Locations	Example Name	Example Location
pub const UTC_PLUS_14: usize = 0; //	Christmas Island/Kiribati	LINT	Kiritimati
pub const UTC_PLUS_13: usize = 1; // Tonga and 3 more	TOT	Nukualofa
pub const UTC_PLUS_12_45: usize = 2; // Chatham Islands/New Zealand	CHAST	Chatham Islands
pub const UTC_PLUS_12: usize = 3; // New Zealand with exceptions and 9 more	ANAT	Anadyr
pub const UTC_PLUS_11: usize = 4; // small region of Russia and 6 more	SBT	Honiara
pub const UTC_PLUS_10_30: usize = 5; // Lord Howe Island/Australia	LHST	Lord Howe Island
pub const UTC_PLUS_10: usize = 6; // much of Australia and 6 more	AEST	Melbourne
pub const UTC_PLUS_9_30: usize = 7; // some regions of Australia	ACST	Adelaide
pub const UTC_PLUS_9: usize = 8; // Japan, South Korea and 5 more	JST	Tokyo
pub const UTC_PLUS_8_45: usize = 9; // Western Australia/Australia	ACWST	Eucla
pub const UTC_PLUS_8: usize = 10; // China, Philippines and 11 more	CST	Beijing
pub const UTC_PLUS_7: usize = 11; // much of Indonesia, Thailand and 7 more	WIB	Jakarta
pub const UTC_PLUS_6_30: usize = 12; // Myanmar and Cocos Islands	MMT	Yangon
pub const UTC_PLUS_6: usize = 13; // Bangladesh and 6 more	BST	Dhaka
pub const UTC_PLUS_5_45: usize = 14; // Nepal	NPT	Kathmandu
pub const UTC_PLUS_5_30: usize = 15; // India and Sri Lanka	IST	New Delhi
pub const UTC_PLUS_5: usize = 16; // Pakistan and 8 more	UZT	Tashkent
pub const UTC_PLUS_4_30: usize = 17; // Afghanistan	AFT	Kabul
pub const UTC_PLUS_4: usize = 18; // Azerbaijan and 8 more	GST	Dubai
pub const UTC_PLUS_3_30: usize = 19; // Iran	IRST	Tehran
pub const UTC_PLUS_3: usize = 20; // Greece and 37 more	MSK	Moscow
pub const UTC_PLUS_2: usize = 21; // Germany and 47 more	CEST	Brussels
pub const UTC_PLUS_1: usize = 22; // United Kingdom and 23 more	BST	London
pub const UTC_PLUS_0: usize = 23; // Iceland and 16 more	GMT	Accra
pub const UTC_MINUS_1: usize = 24; // Cabo Verde	CVT	Praia
pub const UTC_MINUS_2: usize = 25; // most of Greenland and 3 more	WGST	Nuuk
pub const UTC_MINUS_2_30: usize = 26; // Newfoundland and Labrador/Canada	NDT	St. John's
pub const UTC_MINUS_3: usize = 27; // most of Brazil, Argentina and 9 more	ART	Buenos Aires
pub const UTC_MINUS_4: usize = 28; // regions of USA and 32 more	EDT	New York
pub const UTC_MINUS_5: usize = 29; // regions of USA and 10 more	CDT	Mexico City
pub const UTC_MINUS_6: usize = 30; // small region of USA and 9 more	CST	Guatemala City
pub const UTC_MINUS_7: usize = 31; // regions of USA and 2 more	PDT	Los Angeles
pub const UTC_MINUS_8: usize = 32; // Alaska/USA and 2 more	AKDT	Anchorage
pub const UTC_MINUS_9: usize = 33; // Alaska/USA and regions of French Polynesia	HDT	Adak
pub const UTC_MINUS_9_30: usize = 34; // Marquesas Islands/French Polynesia	MART	Taiohae
pub const UTC_MINUS_10: usize = 35; // Hawaii/USA and 2 more	HST	Honolulu
pub const UTC_MINUS_11: usize = 36; // American Samoa and 2 more	NUT	Alofi
pub const UTC_MINUS_12: usize = 37; // much of US Minor Outlying Islands	AoE	Baker Island
pub const ALL_TIME_ZONES: usize = 38; // all time zones
