use common::model::response::RESPONSE_INVALID_DATA_FORMAT_FLAG;
use common::model::response::RESPONSE_INVALID_FLAG;
use common::model::response::RESPONSE_INVALID_GLOBAL_CATEGORY_ID_FLAG;
use common::model::response::RESPONSE_INVALID_CATEGORY_CACHE_INDEX_FLAG;
use common::model::response::RESPONSE_INVALID_GLOBAL_LOCATION_ID_FLAG;
use common::model::response::RESPONSE_INVALID_LOCATION_CACHE_INDEX_FLAG;
use common::model::response::RESPONSE_INVALID_PERIOD_ID_FLAG;
use common::model::response::RESPONSE_INVALID_TIMEZONE_ID_FLAG;

pub const INVALID_DATA_FORMAT_RESPONSE: [u8; 1] = [RESPONSE_INVALID_FLAG + RESPONSE_INVALID_DATA_FORMAT_FLAG];
pub const INVALID_GLOBAL_CATEGORY_ID_RESPONSE: [u8; 1] = [RESPONSE_INVALID_FLAG + RESPONSE_INVALID_GLOBAL_CATEGORY_ID_FLAG];
pub const INVALID_CATEGORY_CACHE_INDEX_RESPONSE: [u8; 1] = [RESPONSE_INVALID_FLAG + RESPONSE_INVALID_CATEGORY_CACHE_INDEX_FLAG];
pub const INVALID_GLOBAL_LOCATION_ID_RESPONSE: [u8; 1] = [RESPONSE_INVALID_FLAG + RESPONSE_INVALID_GLOBAL_LOCATION_ID_FLAG];
pub const INVALID_LOCATION_CACHE_INDEX_RESPONSE: [u8; 1] = [RESPONSE_INVALID_FLAG + RESPONSE_INVALID_LOCATION_CACHE_INDEX_FLAG];
pub const INVALID_PERIOD_ID_RESPONSE: [u8; 1] = [RESPONSE_INVALID_FLAG + RESPONSE_INVALID_PERIOD_ID_FLAG];
pub const INVALID_TIMEZONE_ID_RESPONSE: [u8; 1] = [RESPONSE_INVALID_FLAG + RESPONSE_INVALID_TIMEZONE_ID_FLAG];

